# Generated by Django 5.0.6 on 2024-06-25 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('team_name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=70)),
                ('headshot', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.TextField(max_length=70)),
                ('year', models.IntegerField()),
                ('race_start', models.DateTimeField()),
                ('session_key', models.IntegerField()),
            ],
            options={
                'ordering': ['-race_start'],
            },
        ),
        migrations.CreateModel(
            name='GroupJoinRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('successful_predicts', models.IntegerField(default=0)),
                ('almost_predicts', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictions_json', models.TextField()),
                ('race', models.TextField(max_length=70)),
                ('year', models.IntegerField()),
                ('points_gained', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('race_vinculated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.raceinformation')),
            ],
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(max_length=1000)),
                ('race_vinculated', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.raceinformation')),
            ],
        ),
    ]
