# Generated by Django 5.0.6 on 2024-06-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_groupdetails_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['points']},
        ),
    ]
